### ISSUE TITLE
SDK v3.2 fails CMAKE with error "Target dependency djiosdk-wrapper not found"

### ISSUE THREAD

**Issue by taurean1192** [dji-sdk/Onboard-SDK#84] opened 2016-12-30 11:12 UTC
The instructions on the readme page, lead to an error in compilation via CMAKE - Target dependency not found

**Comment by zliDJI** [comment] 2017-01-03 23:31
Hi, taurean1192. What onboard computer and OS version are you using?

**Comment by taurean1192** [comment] 2017-01-04 06:14
I am using a Raspberry Pi 3 (Arm 64 bit), running the Raspbian Jessie.

I also tried using Ubuntu 16.04 Arm version but it failed.

I also did the same with my x64 laptop running Ubuntu 16.04 but it failed
there as well.

**Comment by wellsa1** [comment] 2017-01-04 13:44
I have the same issue on Raspbian Jessie.  Haven't found a work-around yet.

**Comment by zliDJI** [comment] 2017-01-04 18:04
Please try to cd to the top level Onboard-SDK, and then
mkdir build
cd build
cmake ..
make

**Comment by taurean1192** [comment] 2017-01-04 18:17
I did that as well. The executable is then created in 'build/bin'

On running it, after pasting a copy of UserConfig.txt, it doesn't recognise
the mode LB2 is in and gives the error that RC is not in mode P, something
we observed in v3.1.9

**Comment by zliDJI** [comment] 2017-01-04 18:35
Hi, taurean1192, could you post a picture of your error?

Also, I assume you are running the latest firmware, and the RC is in F mode, right?

**Comment by wellsa1** [comment] 2017-01-04 18:41
This will only work on Ubuntu right?  I'm failing the cmake since it can't find a distro version that matches the *.cmake 16.04, 14.04 or 18.

**Comment by taurean1192** [comment] 2017-01-04 18:47
No I had the RC in P mode for the latest firmware. The instructions said to keep the it in P mode for FW 1.5 in A3. 
![sdk_err](https://cloud.githubusercontent.com/assets/24839780/21654589/2c71ba24-d2dc-11e6-8a10-e1f5199c7ae1.jpg)

**Comment by zliDJI** [comment] 2017-01-04 22:37
Hi @taurean1192, I tried to reproduce your problem but was not able to. Please check in DJI GO if your firmware matches mine: Aircraft 1.3.0.00+ (it's actually 1.5 from dji assistant 2),  RC (1.1.70), LB2Air(1.1.2.00).

At the same time, could you delete your above post  and start a new issue, since this is a different problem.

I assume that by running cmake at top level, you don't have "Target dependency djiosdk-wrapper not found" issue any more, right?

Thanks!

**Comment by taurean1192** [comment] 2017-01-05 05:04
Hi @zliDJI I have the A3 (FW 1.5), LB2 Air (v1.1.4) and LB2 RC at (latest fw). You think this could be a possible issue?

**Comment by taurean1192** [comment] 2017-01-05 05:31
Also when compiling the v3.2 SDK over 14.04 , on doing CMAKE over the top level, it throws the following error - 

`if given arguements:

"GTEST" "OR" "(" "USE_PRECISION_MISSIONS" "AND" "(" "STREQUAL" "1604" ")" ")"

Unknown arguments specified

-- Configuring incomplete, errors occurred!`

**Comment by taurean1192** [comment] 2017-01-05 05:47
I just tried it on Ubuntu 14.04 (ARM 32 bit), the CMAKE inside sample/Linux/Blocking/build works without errors, but make throws the following error - 

`
![make_err](https://cloud.githubusercontent.com/assets/24839780/21670195/6a41e9b2-d338-11e6-90f4-9e21eacefe23.jpg)
`

**Comment by taurean1192** [comment] 2017-01-05 13:30
I am adding a screenshot of the latest errors, please see this
![dji_sdk_3_2](https://cloud.githubusercontent.com/assets/24839780/21682194/43a7058a-d379-11e6-86c6-54c57098cd80.png)

**Comment by zliDJI** [comment] 2017-01-05 21:34
Hi, @taurean1192 , with x86-64 ubuntu 1604, please run cmake at the top level build folder instead of sample/Linux/Blocking/build  

On manifold ubuntu 14.04, we just fixed a cmake bug and is currently testing. Will push in a couple of hours. Sorry about that.

**Comment by zliDJI** [comment] 2017-01-06 17:39
@taurean1192  We have pushed some cmake changes. Could you try to build to see if they solved your problem?

@wellsa1 You should be able to build (without advanced features) on Pi. Please let us known. Thanks!

**Comment by taurean1192** [comment] 2017-01-07 11:42
@zliDJI these are snapshots for a RPi 3 (64 bit ARM) running Raspbian Jessie (Debian 8.6). I tried build both at top level and at the 'sample/Linux/Blocking/build' levels
![2017-01-07-135551_1360x768_scrot](https://cloud.githubusercontent.com/assets/24839780/21741456/2d0b6de6-d4fc-11e6-8000-e75cc647a646.png)
![2017-01-07-135803_1360x768_scrot](https://cloud.githubusercontent.com/assets/24839780/21741455/2d0acce2-d4fc-11e6-809a-41457d0372df.png)

Then I treid doing this on Ubuntu 16.04 running on RPi 3, the following error comes - the same comes on my x64 Ubuntu machine. I updated A3 to latest FW v1.6, DJI Assistant 2 v1.0.9 but nothing changed. Is it possible that my LB2 is faulty

![2017-01-07-170615_1360x768_scrot](https://cloud.githubusercontent.com/assets/24839780/21741468/73149f10-d4fc-11e6-8adb-c231d7a78a61.png)

**Comment by wellsa1** [comment] 2017-01-10 21:41
I have the same errors as taurean attempting cmake with the Non-Blocking version and at the root.  Rasberry pi Jessie ARM 64.  It appears nothing changed.

**Comment by zliDJI** [comment] 2017-01-12 17:32
We pushed a branch "raspberrypi-support", and we have tested to build linux sample on raspberrypi 2. Please check it out and give it a shot. Thanks!

**Comment by rohitsantdji** [comment] 2017-01-23 23:09
Closing this issue. If errors persist, please reopen this issue or start a new one depending on the nature of the error.

**Closed by rohitsantdji** 2017-01-23 23:09 UTC
