### ISSUE TITLE
Load All Waypoints always fails!

### ISSUE THREAD

**Issue by kezhengtao** [dji-sdk/Onboard-SDK#241] opened 2018-02-06 01:23 UTC
Please refer to the attachment.
[LoadAllWaypointsFails.zip](https://github.com/dji-sdk/Onboard-SDK/files/1697389/LoadAllWaypointsFails.zip)

**Comment by rohitsantdji** [comment] 2018-02-06 02:15
Can you connect RC and mobile device, and let us know if there are any requests from DJI Go to sign in?

**Comment by kezhengtao** [comment] 2018-02-06 05:45
Yes ,I have connected RC. 
Please look at the content in the video,RC Status is P.

**Comment by kezhengtao** [comment] 2018-02-06 05:55
Is my  operation flow wrong?

**Comment by rohitsantdji** [comment] 2018-02-06 07:07
Your operation flow seems okay - does DJI Go ask you to sign in or provide any other prompts?

**Comment by kezhengtao** [comment] 2018-02-06 07:24
I just open RC in this test.Not open DJI go. I  think I can use QT instead of DJI Go in the test.
I will open DJI go next time to see prompts .

**Comment by rohitsantdji** [comment] 2018-02-06 12:32
I believe we found the cause of your error - In your workflow, you can avoid pressing the "Read Position as View Point" button, it is buggy. The "Add Waypoint" button should add the current drone location by default, even without pressing the "Read Position as View Point" button. Let us know if this fixes it.

**Comment by kezhengtao** [comment] 2018-02-07 05:14
Ye,You've just said a mouthful!Thanks

**Comment by kezhengtao** [comment] 2018-02-08 01:30
Could you tell me why?





在 2018-02-06 20:32:55，"Rohit Sant" <notifications@github.com> 写道：


I believe we found the cause of your error - In your workflow, you can avoid pressing the "Read Position as View Point" button, it is buggy. The "Add Waypoint" button should add the current drone location by default, even without pressing the "Read Position as View Point" button. Let us know if this fixes it.

**Comment by rohitsantdji** [comment] 2018-03-06 02:21
We would need to investigate further. Since your original problem (not being able to upload waypoints) has a workaround, I'm going to go ahead and close this issue.

**Closed by rohitsantdji** 2018-03-06 02:21 UTC
