### ISSUE TITLE
A Djiosdk-qt-sample Bug

### ISSUE THREAD

**Issue by Changel321** [dji-sdk/Onboard-SDK#286] opened 2018-04-03 00:57 UTC
The M100 is connected to the computer through the UART interface. When running the Qt version of the Onboard SDK, the bug "QObject: Cannot create children for a parent that is in a different thread.(Parent is QSerialPort(0x1e234da01c0), parent' s thread is QThread(0x1e235d04250), current thread is QThread(0x1e2308b9800)" appears. How does this problem be solved?

**Comment by imkhairulikhwan** [comment] 2018-04-12 02:02
Hi Rohit, 

thank you for the clarification, since it's a workaround, does that mean we can continue using the sample and it will work as intended, without have to update the code?

**Comment by hummelslei** [comment] 2019-05-31 08:54
Close this issue now. If you still have more issues related to DJI SDK, please help to fill in this form: 
https://formcrafts.com/a/dji-developer-feedback-en to report them to DJI Developer Support. Thanks for your understanding and cooperation.

**Closed by hummelslei** 2019-05-31 08:54 UTC
