### ISSUE TITLE
FlightAnomaly wrong values

### ISSUE THREAD

**Issue by deadman2000** [dji-sdk/Onboard-SDK#732] opened 2021-02-19 09:03 UTC
M300 always send abnormally value of aircraftIsFalling = 1

**Comment by dji-dev** [comment] 2021-02-20 03:14
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/44041'>Zendesk ticket #44041</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

What is the state of the aircraft when you get abnormal value: aircraftIsFalling = 1? Is it a real flight state or a problem found in the simulator?

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team

**Comment by deadman2000** [comment] 2021-02-20 07:17
In all states. When engines is off and in flight. In simulation and in real flight

**Comment by dji-dev** [comment] 2021-02-20 08:05
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/44041'>Zendesk ticket #44041</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

We have submitted this issue for further confirmation. If there is any result, we will promptly feedback with you.

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team

**Comment by dji-dev** [comment] 2021-04-13 06:22
Agent comment from kyle.cai in <a href='https://djisdksupport.zendesk.com/agent/tickets/44041'>Zendesk ticket #44041</a>:<br><br>Dear developer ,

Thank you for contacting DJI.

The issue is expected to be fixed in June with new firmware（M300）.

Thank you for your understanding and support, hope you have a nice day.

Best Regards,
DJI SDK Support Team

**Closed** 2022-03-31 03:14 UTC
