### ISSUE TITLE
A3 - OnboardSDK version mismatch.

### ISSUE THREAD

**Issue by SodanKerjuu** [dji-sdk/Onboard-SDK#91] opened 2017-01-27 10:32 UTC
Latest A3 firmware doesn't recognize latest OnboardSDK version.
Tested both with fresh installs + factory settings.

"Your SDK version does not match the one reported by the drone."

I tried all version possibilities to the UserConfig.txt, most logical one being "VersionA3_32"

**Comment by rohitsantdji** [comment] 2017-01-27 19:59
Duplicate of #88

**Closed by rohitsantdji** 2017-01-27 19:59 UTC
